# Generated by Django 6.0.5 on 2026-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_department_hospital_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
